### ISSUE TITLE
No unit test?

### ISSUE THREAD

**Issue by haruelrovix** [afbrilian/facebook-chat-bot#1]
Hi @afbrilian 👋 

I'm Havit, Director of Engineering at AdaKerja.

In the task requirements, _What we look at_ section, we mention `tested code`. Unfortunately, I found `coverageDirectory` in `package.json` file but no unit tests in the repository.

Could you please add some unit tests?

Thanks.
-Havit

**Comment by afbrilian** [comment]
Hi @haruelrovix 
aaah my bad, I thought tested means manually tested and able to run. 
Sure, will add some unit tests and push it to the repo 🙇 

Thanks,

**Comment by afbrilian** [comment]
Hi @haruelrovix 
I have add the unit test classes and thank you for the reminder 🙇 
I will close this issue and let me know if there is anything I need to do.

Thanks
